name: 29910 Deploy

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  REPONAME: vaja5

on:
  workflow_run:
    workflows:
      - 29910 Test
    types:
      - completed

jobs:
  deploy:
    name: Zgradi in objavi Docker image
    runs-on: [self-hosted, linux]

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Prenesi repozitorij
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Ustvari datum za tag
        run: echo "DATE_TAG=$(date +'%Y-%m-%d--%H-%M-%S')" >> "$GITHUB_ENV"

      - name: Prijava v DockerHub
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Zgradi Docker image
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.REPONAME }}:latest \
                       -t ${{ env.DOCKER_USERNAME }}/${{ env.REPONAME }}:${{ env.DATE_TAG }} .

      - name: Potisni Docker image
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.REPONAME }}:latest
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.REPONAME }}:${{ env.DATE_TAG }}
